package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/kohdice/poke-graphql/internal/graphql/model"
)

// Pokemon is the resolver for the pokemon field.
func (r *queryResolver) Pokemon(ctx context.Context) (*model.Pokemon, error) {
	return &model.Pokemon{
		ID:                    "ExampleID",
		NationalPokedexNumber: 1,
		Name:                  "フシギダネ",
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
